name: Publish CI

on:
  release:
    types: [created]

env:
  DOCKER_HUB_USERNAME: srfaytkn
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  REPOSITORY: srfaytkn/spotify-auth-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Build
        run: go build -v -o spotify-auth-service .
      - name: Login to docker
        run: docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_TOKEN
      - name: Build and push
        run: |
          appVersion="$(cat .version)"
          docker build -t $REPOSITORY:$appVersion -t $REPOSITORY:latest .
          docker push $REPOSITORY:$appVersion
          docker push $REPOSITORY:latest
      - name: Logout of docker
        if: always()
        run: docker logout
